/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_wgputoyrenderer_free(a: number): void;
export function create_renderer(a: number, b: number, c: number, d: number): number;
export function wgputoyrenderer_render(a: number): void;
export function wgputoyrenderer_prelude(a: number, b: number): void;
export function wgputoyrenderer_preprocess(a: number, b: number, c: number): number;
export function wgputoyrenderer_compile(a: number, b: number): void;
export function wgputoyrenderer_set_time_elapsed(a: number, b: number): void;
export function wgputoyrenderer_set_time_delta(a: number, b: number): void;
export function wgputoyrenderer_set_mouse_pos(a: number, b: number, c: number): void;
export function wgputoyrenderer_set_mouse_click(a: number, b: number): void;
export function wgputoyrenderer_set_keydown(a: number, b: number, c: number): void;
export function wgputoyrenderer_set_custom_floats(a: number, b: number, c: number, d: number, e: number): void;
export function wgputoyrenderer_set_pass_f32(a: number, b: number): void;
export function wgputoyrenderer_resize(a: number, b: number, c: number, d: number): void;
export function wgputoyrenderer_reset(a: number): void;
export function wgputoyrenderer_on_success(a: number, b: number): void;
export function wgputoyrenderer_load_channel(a: number, b: number, c: number, d: number): void;
export function wgputoyrenderer_load_channel_hdr(a: number, b: number, c: number, d: number, e: number): void;
export function __wbg_sourcemap_free(a: number): void;
export function __wbindgen_malloc(a: number, b: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number, d: number): number;
export const __wbindgen_export_2: WebAssembly.Table;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h5f79bf1caa58a081(a: number, b: number, c: number): void;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h71756065329dd073(a: number, b: number, c: number): void;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_free(a: number, b: number, c: number): void;
export function __wbindgen_exn_store(a: number): void;
export function wasm_bindgen__convert__closures__invoke2_mut__h5e291eb4dc40e0fa(a: number, b: number, c: number, d: number): void;
